### PR TITLE
Add support for dimming of light bulbs.

### LINKED ISSUE #8: Dim Light Bulbs
Dear developer,

Great work. Plugin works like a charm. I used it with a few Wall Outlets.

Question: Is it possible to dim a light bulb with this Plugin? I want to buy suchs bulbs, but I want to be sure it works? 

Sorry. Just read the description in Domoticz that only power plugs can be discovered and used.
Can you make a change to these plugin so that dimming and on/off bulbs is possible?

Thanks in advantage.

### PR DESCRIPTION
**Pull request by tizzen33**
Light is now added as Domoticz device 'Dimmer' instead of a simple switch and setBrightness added in the commands.

*** Not yet tested ***

### CODE REVIEW

**Comment by michelscholte** [comment]
Hi, 

thanks for your effort and quick response. 
Accidentally bought a lamp an hour ago :-).

I will test it at the end of the day and let you if it works.

Regards,
Michel

**Comment by michelscholte** [comment]
Hi,

I've tested the new release with a dimmable light.
The plugin detect it, but not as dimmer. It will be detected as "Type: Light/Switch" , "SubType: Switch". 
If I change it to "Dimmer" in Domoticz, I can switch the light on/off, but the dimmer slider doesn't work unfortunately.

Hopefully you have a clue.

Thanks

**Comment by tizzen33** [comment]
Hi, did you pull the latest version from the patch-1 branch? [https://github.com/tizzen33/domoticz-tuyacloud-plugin/tree/tizzen33-patch-1](https://github.com/tizzen33/domoticz-tuyacloud-plugin/tree/tizzen33-patch-1)
The master branch doesn't have this feature yet as I'm implementing another device type.

**Comment by michelscholte** [comment]
I'm sorry I forget that. 
I've done it now. The new added light can not set to On/Off and can't be dimmed. I'm getting the following errors in de Domoticz log:

2020-08-17 18:25:43.804 Error: (Tuya Cloud) 'onCommand' failed 'TypeError':'can only concatenate str (not "int") to str'.
2020-08-17 18:25:43.804 Error: (Tuya Cloud) ----> Line 221 in '/home/pi/domoticz/plugins/domoticz-tuyacloud-plugin/plugin.py', function onCommand
2020-08-17 18:25:43.804 Error: (Tuya Cloud) ----> Line 173 in '/home/pi/domoticz/plugins/domoticz-tuyacloud-plugin/plugin.py', function onCommand
2020-08-17 18:25:47.571 Status: User: Admin initiated a switch command (2506/Tuya Cloud - A65 CCT/Set Level)
2020-08-17 18:25:47.714 Error: (Tuya Cloud) 'onCommand' failed 'TypeError':'can only concatenate str (not "int") to str'.
2020-08-17 18:25:47.714 Error: (Tuya Cloud) ----> Line 221 in '/home/pi/domoticz/plugins/domoticz-tuyacloud-plugin/plugin.py', function onCommand
2020-08-17 18:25:47.714 Error: (Tuya Cloud) ----> Line 173 in '/home/pi/domoticz/plugins/domoticz-tuyacloud-plugin/plugin.py', function onCommand

**Comment by tizzen33** [comment]
Can you retry?

**Comment by michelscholte** [comment]
Hi Tizzen,

Cannot switch On/Off or dim. Error in Domoticz: 

2020-08-17 18:50:48.163 (Tuya Cloud) Command failed: turnOnOff, value: 1
2020-08-17 18:50:48.163 (Tuya Cloud) Tuya error code: NoSuchTarget
2020-08-17 18:50:48.034 Status: User: Admin initiated a switch command (2506/Tuya Cloud - A65 CCT/On)
2020-08-17 18:50:50.234 (Tuya Cloud) Command failed: turnOnOff, value: 1
2020-08-17 18:50:50.234 (Tuya Cloud) Tuya error code: NoSuchTarget
2020-08-17 18:50:50.094 Status: User: Admin initiated a switch command (2506/Tuya Cloud - A65 CCT/On)
2020-08-17 19:00:02.972 (Tuya Cloud) Command failed: setBrightness, value: 29
2020-08-17 19:00:02.972 (Tuya Cloud) Tuya error code: DependentServiceUnavailable
2020-08-17 19:00:02.635 Status: User: Admin initiated a switch command (2506/Tuya Cloud - A65 CCT/Set Level)

**Comment by michelscholte** [comment]
Hi,

I think the in Domoticz created ID is not correct. The ID is 050475012462ab4c4eb3 from Tuya and every time I disabled and enabled the plugin it creates a new device with a random ID in Domoticz:

2507 | Tuya Cloud | 00170005 | 5 | Tuya Cloud - A65 CCT | Light/Switch | Switch | Off
-- | -- | -- | -- | -- | -- | -- | --
2506 | Tuya Cloud | 00170004 | 4 | Tuya Cloud - A65 CCT | Light/Switch | Switch | Off
-- | -- | -- | -- | -- | -- | -- | --










2020-08-17 20:50:35.833 Status: (Tuya Cloud) Initialized version 0.1, author 'tizzen33'
2020-08-17 20:50:36.050 (Tuya Cloud) Devices found:[{"data": {"online": true, "state": true}, "name": "Raspberry Pi Domoticz", "icon": "https://images.tuyaeu.com/smart/icon/ay1533895021982bN2sO/1585648992e5e0cf5f272.png", "id": "534138002462ab53cea9", "dev_type": "switch", "ha_type": "switch"}, {"data": {"online": true, "state": false}, "name": "Haard", "icon": "https://images.tuyaeu.com/smart/icon/ay1533895021982bN2sO/1585648992e5e0cf5f272.png", "id": "53413800c82b964903a5", "dev_type": "switch", "ha_type": "switch"}, {"data": {"brightness": "591", "color_mode": "white", "online": true, "state": "true", "color_temp": 19953}, "name": "A65 CCT", "icon": "https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/1591927389ad533b2820e.png", "id": "050475012462ab4c4eb3", "dev_type": "light", "ha_type": "light"}]
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through tuya devices
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through Domoticz Devices
2020-08-17 20:50:36.050 (Tuya Cloud) Device with identifier 534138002462ab53cea9 already exists.
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through tuya devices
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through Domoticz Devices
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through Domoticz Devices
2020-08-17 20:50:36.050 (Tuya Cloud) Device with identifier 53413800c82b964903a5 already exists.
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through tuya devices
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through Domoticz Devices
2020-08-17 20:50:36.050 (Tuya Cloud) Looping through Domoticz Devices
2020-08-17 20:50:36.051 (Tuya Cloud) Creating a light device with identifier 050475012462ab4c4eb3
2020-08-17 20:50:36.314 (Tuya Cloud) Tuya Cloud devices initialized.

**Comment by tizzen33** [comment]
I was thinking the same thing because of the 'noSuchTarget' error. It seems I forgot to add the Tuya ID to the Domoticz light device. That should be fixed now. I think we're getting closer :)

**Comment by michelscholte** [comment]
Hi,

Closer and closer :-).  Now I'm getting a DependServiceUnavailable:

2020-08-18 12:35:25.656 (Tuya Cloud) Command failed: setBrightness, value: 37
2020-08-18 12:35:25.656 (Tuya Cloud) Tuya error code: DependentServiceUnavailable
2020-08-18 12:35:25.501 Status: User: Admin initiated a switch command (2512/Tuya Cloud - A65 CCT/Set Level)

**Comment by tizzen33** [comment]
And what about On/Off?

**Comment by michelscholte** [comment]
On/Off is working.

**Comment by tizzen33** [comment]
Perfect! I've changed the command to set Brightness, try once more?

**Comment by michelscholte** [comment]
Yes. Dimming is working. Great.  

Only  one little thing. Hopefully I'm not asking too much.

27% in Domoticz is 1% in Tuya app.
100% in Domoticz is 33% in Tuya app.

**Comment by tizzen33** [comment]
I tought this was going to be next problem. Try again?

**Comment by michelscholte** [comment]
I can now dim much better. 

11% in Domoticz is 1% in Tuya app
100% in Domoticz is 100% in Tuya app.

But now I have a strange behavior. When I change the slider in Domoticz, the dim percent is adjusted , but the slider falls back to the begin and the bulb icon is getting off. Bulbs itself stays at on with the adjusted dim perc.

**Comment by tizzen33** [comment]
Immediately or after 30 seconds? The behaviour of setting is brightness is different from On/Off I think. I've done a small change.

**Comment by michelscholte** [comment]
It was immediately.
After install latest update Domoticz is holding the slider at the adjusted position. Only when I turn the bulb Off, the icon in Domoticz still shows On. After  about 2 minutes the Icon shows Off.

**Comment by michelscholte** [comment]
Yes. Now it's working.

Thank you very much.

**Comment by tizzen33** [comment]
No problem. I've merged this into the master branch.

**Pull request merged**
